//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public Dishes()
        {
            this.Dish_Composition = new HashSet<Dish_Composition>();
        }
    
        public int ID { get; set; }
        public string Dish_name { get; set; }
        public Nullable<int> ID_Group { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID_Photo { get; set; }
    
        public virtual ICollection<Dish_Composition> Dish_Composition { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Photos Photos { get; set; }
    }
}
