//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish_Composition
    {
        public int ID { get; set; }
        public Nullable<int> ID_Dish { get; set; }
        public Nullable<int> ID_Ingredient { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Ingredients Ingredients { get; set; }
    }
}
