//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public Ingredients()
        {
            this.Dish_Composition = new HashSet<Dish_Composition>();
        }
    
        public int ID { get; set; }
        public string Ingredient_name { get; set; }
    
        public virtual ICollection<Dish_Composition> Dish_Composition { get; set; }
    }
}
